import sys
import os
import logging 
from pyspark.sql import SparkSession, DataFrame
from pyspark.sql.types import *
from pyspark.sql.functions import *



# --- Logging Setup ---
# Define the directory and file path for the log file INSIDE the container.
# This path should be within the volume mounted from your host's local 'log' directory.
# Ensure the log directory exists inside the container before configuring the logger.
CONTAINER_LOG_DIR = "/app/log" # Directory where logs will be mounted inside the container
LOG_FILE_PATH = os.path.join(CONTAINER_LOG_DIR, "spark-stream.log") # Full path to the log file




# Configure the basic logger for writing to a file.
# Messages with level INFO or higher will be written to the specified file.
# The format includes timestamp, log level, and the message.
logging.basicConfig(level=logging.INFO,
                    format='%(asctime)s - %(levelname)s - %(message)s',
                    filename=LOG_FILE_PATH, # Specify the log file path
                    filemode='a') # Append to the log file if it already exists

# Adding a handler to also output logs to the console (stdout/stderr) for visibility via 'docker compose logs'. This is very helpful for debugging.

console_handler = logging.StreamHandler(sys.stdout)
console_handler.setLevel(logging.INFO) # Set level for console output
formatter = logging.Formatter('%(asctime)s - %(levelname)s - %(message)s') # Same format as file
console_handler.setFormatter(formatter)
# Prevent adding handlers multiple times if the script is somehow reloaded
# Also check if handlers already exist to avoid duplicates on potential re-configs
if not logging.getLogger().handlers:
     logging.getLogger().addHandler(console_handler)
# If handlers already exist (e.g., from a previous basicConfig), ensure our handlers are present
else:
    # Check if file handler is already added
    if not any(isinstance(h, logging.FileHandler) and h.baseFilename == LOG_FILE_PATH for h in logging.getLogger().handlers):
         logging.getLogger().addHandler(logging.FileHandler(filename=LOG_FILE_PATH, mode='a', encoding=None, delay=False))
    # Check if console handler is already added (a bit trickier to check for StreamHandler to sys.stdout specifically)
    # For simplicity, if handlers exist, we'll just assume basicConfig was already called and console is handled,
    # or you might need more advanced logging configuration logic for complex scenarios.
    pass


# Define the schema matching the CSV files generated by generator.py
# This schema must match the structure BEFORE transformations.

stream_schema = StructType([
    StructField("customer_id", StringType(), True),
    StructField("first_name", StringType(), True),
    StructField("last_name", StringType(), True),
    StructField("age", IntegerType(), True),
    StructField("order_id", StringType(), True),
    StructField("time_stamp", TimestampType(), True), 
    StructField("Total quantity", IntegerType(), True),
    StructField("Total Price", FloatType(), True),
    StructField("product_id", StringType(), True),
    StructField("product_name", StringType(), True),
    StructField("quantity", IntegerType(), True),
    StructField("unit_price", FloatType(), True),
    StructField("Total Item Price", FloatType(), True)
])

# --- Configuration from Environment Variables ---
# Get database connection details and other config from environment variables
# These should be set in your docker-compose.yml environment block, sourcing from .env
POSTGRES_URL = os.environ.get("POSTGRES_URL")
POSTGRES_USER = os.environ.get("POSTGRES_USER") 
POSTGRES_PASSWORD = os.environ.get("POSTGRES_PASSWORD") 
POSTGRES_TABLE = os.environ.get("POSTGRES_TABLE") 

# Checkpoint location within the mounted data volume (CRITICAL for streaming)
# Ensure this path is writable by the Spark user in the container

CHECKPOINT_LOCATION = "/opt/spark/data/checkpoints"

# Source data directory (mounted from ./data)
# Spark will monitor this directory for new files
DATA_SOURCE_PATH = "/opt/spark/data"


# --- Input Validation ---
# Check the variables that are actually read. Use logging for errors.
if not all([POSTGRES_URL, POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_TABLE]):
    logging.error(
        "ERROR: Database connection or table environment variables "
        "(POSTGRES_URL, POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_TABLE) must be set."
    )
    sys.exit(1)


# --- Create SparkSession ---
# This is the entry point for all Spark functionality.
# Configure the application name and include the PostgreSQL JDBC driver JAR.
logging.info("Creating SparkSession...")
spark = (SparkSession.builder 
    .appName("PurchaseDataStreamToPostgres") 
    .config("spark.jars", "/opt/spark/jars/postgresql-42.7.5.jar") # Path to the JDBC driver JAR inside the container
    .getOrCreate())

# Optional: Adjust logging level for Spark itself.
spark.sparkContext.setLogLevel("WARN") # WARN or higher will be logged by Spark's internal logger

logging.info(f"SparkSession created. Monitoring {DATA_SOURCE_PATH} for new data.")

# --- Define Streaming Source ---
# Configure Spark to read CSV files from the specified data directory as a stream.
logging.info(f"Defining streaming source from {DATA_SOURCE_PATH}...")
streaming_df = (spark.readStream
    .format("csv")
    .schema(stream_schema) # Apply the schema
    .option("maxFilesPerTrigger", 1) # Process max 1 new file per trigger
    .option("header", "true") # CSVs have headers
    .load(DATA_SOURCE_PATH)) # Path to monitor

logging.info("Streaming source defined. Applying transformations...")

# --- Apply Transformations ---
# Select columns and apply transformations.
transformed_df = streaming_df.select(
    # Remove "CUST-" prefix and alias to match SQL
    regexp_replace(col("customer_id"), "CUST-", "").alias("customer_id"),
    col("first_name"),
    col("last_name"),
    col("age"),
    # Remove "ORDER-" prefix and alias to match SQL
    regexp_replace(col("order_id"), "ORDER-", "").alias("order_id"),
    col("time_stamp"),
    col("product_id"),
    col("product_name"),
    col("quantity"),
    col("unit_price")
)

logging.info("Transformations applied. Defining JDBC sink using foreachBatch...")

# --- Define Function to Write Each Batch to JDBC ---
# This function is executed by Spark Structured Streaming for every micro-batch.
def write_batch_to_postgres(batch_df: DataFrame, batch_id: int):
    """
    Writes a single micro-batch DataFrame to the PostgreSQL database.

    Args:
        batch_df (DataFrame): The DataFrame containing data for the current micro-batch.
        batch_id (int): The ID of the current micro-batch.
    """
    # Skip writing empty batches
    if batch_df.isEmpty():
        logging.info(f"Batch {batch_id} is empty, skipping write.")
        return

    logging.info(f"Writing batch {batch_id} to {POSTGRES_TABLE}...")

    # JDBC connection properties dictionary - uses env vars read outside this function
    jdbc_connection_properties = {
        "user": POSTGRES_USER,
        "password": POSTGRES_PASSWORD,
        "driver": "org.postgresql.Driver"
    }

    try:
        # Use the standard batch write format within the foreachBatch function.
        (batch_df.write 
            .format("jdbc") 
            .option("url", POSTGRES_URL) 
            .option("dbtable", POSTGRES_TABLE) 
            .options(**jdbc_connection_properties) 
            .mode("append") # Append new rows
            .save()) # Trigger the batch write

        logging.info(f"Successfully wrote batch {batch_id}.")

    except Exception as e:
        # Log the error but keep the stream running (as per your original script's logic).
        logging.error(f"Error writing batch {batch_id}: {e}", exc_info=True)


# --- Define Streaming Sink using foreachBatch ---
# Use the foreachBatch sink and provide the write function.
logging.info("Starting streaming query...")
try:
    query = (transformed_df.writeStream 
        .foreachBatch(write_batch_to_postgres)  # Use foreachBatch sink
        .option("checkpointLocation", CHECKPOINT_LOCATION)  # Path for checkpoint data
        .outputMode("append")  # Output mode
        .start()) # Start the query

    logging.info(f"Streaming query started. Using foreachBatch to write to {POSTGRES_URL} table {POSTGRES_TABLE}.")
    logging.info(f"Checkpointing at {CHECKPOINT_LOCATION}")

    # --- Await Termination ---
    # Keep the script/Spark application running until terminated externally.
    logging.info("Awaiting query termination...")
    query.awaitTermination()

    logging.info("Streaming query terminated gracefully.")

except Exception as e:
    # Catch exceptions that might occur during query startup or termination
    # (e.g., issues connecting to master, checkpoint issues).
    logging.error(f"An error occurred during streaming query setup or termination: {e}", exc_info=True)
    sys.exit(1) # Exit with a non-zero code to indicate failure

logging.info("Script finished.") # This line will only be reached if awaitTermination returns or an exception occurs before it